name: 部署文档

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/docs-scraper.yml'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: 检出main分支下最近一次提交
        uses: actions/checkout@v4

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: 运行构建脚本
        run: pnpm run docs:build

      - name: 设置 Pages
        uses: actions/configure-pages@v5

      - name: 上传 Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src/.vuepress/dist'
          
      - name: 部署至 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
