name: docs-scraper
on:
  push:
    branches:
      - main
    paths:
      - 'src/posts/**'
      - 'docs-scraper-config.json'
jobs:
  docs-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs-scraper-config.json
        uses: actions/checkout@v4
        with:
          path: $(pwd)/docs-scraper
          sparse-checkout: |
            docs-scraper-config.json


      - name: run docs-scraper
        run: |
          docker run -it --rm --name scraper \
              -e MEILISEARCH_HOST_URL='https://search.shaanstar.art' \
              -e MEILISEARCH_API_KEY='${{ secrets.MEILISEARCH_MASTER_KEY }}' \
              -v $(pwd)/docs-scraper/config.json:/docs-scraper/config.json \
              getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json