name: 更新索引

on:
  push:
    branches:
      - main
    paths:
      - 'src/academic/**'
      - 'src/tech/**'
      - 'docs-scraper-config.json'

jobs:
  docs-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: 上传爬虫配置文件
        uses: actions/checkout@v4
        with:
          path: docs-scraper
          sparse-checkout: docs-scraper-config.json

      - name: 运行爬虫
        run: |
          docker run --rm \
              -e MEILISEARCH_HOST_URL='${{ secrets.MEILISEARCH_HOST_URL }}' \
              -e MEILISEARCH_API_KEY='${{ secrets.MEILISEARCH_API_KEY }}' \
              -v $(pwd)/docs-scraper/docs-scraper-config.json:/docs-scraper/config.json \
              getmeili/docs-scraper:latest pipenv run ./docs_scraper config.json